import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav style={{
          backgroundColor: 'yellow',
          padding: '20px',
          border: '5px solid red',
          marginBottom: '20px'
        }}>
          <Link href="/new" style={{
            color: 'purple',
            fontSize: '24px',
            textDecoration: 'underline',
            marginRight: '30px',
            fontFamily: 'Comic Sans MS'
          }}>
            NEW
          </Link>
          <Link href="/drawings" style={{
            color: 'green',
            fontSize: '24px',
            textDecoration: 'underline',
            fontFamily: 'Comic Sans MS'
          }}>
            DRAWINGS
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
